### PR TITLE
Add a column for the countries flag, in emoji format

### PR DESCRIPTION
**Pull request by simonlindberg**
The flag emoji are based on the country ISO3166-1-Alpha-2 code.
I generated the new file with this script.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv

def to_flag_component(letter):
	offset = ord(letter) - ord('A')
	A = ord('\U0001F1E6')
	return chr(A + offset)

def get_flag(header_read, row):
	if not header_read:
		return 'Flag emoji'
	else:
		country_code = row[6]
		country_code_list = list(country_code)
		if not country_code_list:
			return ''
		flag = to_flag_component(country_code_list[0]) + to_flag_component(country_code_list[1]) 
		return flag


with open('data/country-codes.csv', 'r') as csv_file, open('data/country-codes.csv.1', 'w') as new_csv_file:
	reader = csv.reader(csv_file, delimiter=',', quotechar='\"')
	writer = csv.writer(new_csv_file, delimiter=',', quotechar='\"')
	header_read = False

	for row in reader:
		flag = get_flag(header_read, row)
		header_read = True
		row.append(flag)
		writer.writerow(row)
```

### CODE REVIEW

**Comment by anuveyatsu** [comment]
Hi @simonlindberg I think it'd be good if you've committed changed script file. Could you please push another commit into that PR? Thanks!

**Comment by anuveyatsu** [comment]
@simonlindberg hey, any updates? :smile:

**Comment by gradedSystem** [comment]
I guess this could be added later @anuveyatsu

**Comment by anuveyatsu** [comment]
Closing this as inactive - we couldn't get an update from the author of this PR.

**Pull request closed without merging**
