### PR TITLE
Generate and integrate the customary names from Unicode CLDR

### PR DESCRIPTION
**Pull request by hanteng**
Per discussion https://github.com/datasets/country-codes/issues/16

* [data] CLDR_country_name_en.tsv generated that stores a "list of
customary names (plus a country identifier that would allow merging into
the main file) in a separate CSV"
* [scripts] get_country_names_Unicode_CLDR.py written to execute the
construction of the English customary names, plus the join action/update
into the main country list
* [data] country-codes-bak.csv is generated for backup or comparison,
which is optional.

### CODE REVIEW

**Comment by ewheeler** [comment]
Thanks, @hanteng! this looks great

Only thing missing is to update the [datapackage.json file](https://github.com/datasets/country-codes/blob/master/datapackage.json) to include and describe the new column

**Comment by hanteng** [comment]
@ewheeler Thanks for responding. Now I have updated the datapackage.json and README file. Have a look and let me know what you think.

**Comment by ewheeler** [comment]
@hanteng I've given this some more thought and I'm sorry I need to ask for one more thing.

Since the purpose of this dataset is to aggregate various official standards for referring to and representing countries, I think it would be best to retain the official English names from ISO3166 in the dataset. Instead of replacing these with the CLDR customary names, would it be possible to include both such that the CLDR names are in a separate, new column?

I propose that the current `name` column be renamed `official_name` and contain the official ISO3166 English names (and `name_fr` change to `official_name_fr` and contain the official ISO3166 French names). Then propose adding the CLDR customary names in a column called `name`

**Comment by hanteng** [comment]
@ewheeler It is fine (to keep the official English names from ISO3166). I can leave the existing names and the original ISO link (now contains no information) intact.  I can follow your proposed three column proposal when I have more time to do this.

**Comment by hanteng** [comment]
@ewheeler Hi. Done. Have a look.

**Comment by ewheeler** [comment]
@hanteng great! many thanks!

**Pull request merged**
