### PR TITLE
Add new column Wikidata ID

### PR DESCRIPTION
**Pull request by ppKrauss**
Now there are an automatic way to filter Wikidata, use `sh wd_countries.sh` for retrive and filter Wikidata countries, and save it as `wd_countries.csv`. 

Refs.  https://stackoverflow.com/a/51674447/287948

### CODE REVIEW

**Comment by valerio-bozzolan** [comment]
Maybe a better title for this pull request is "Add new column Wikidata ID"

**Comment by gradedSystem** [comment]
I don't think this one relevant because we don't have `scripts/wd_countries.sh` @anuveyatsu we can close this down

**Comment by gradedSystem** [comment]
@anuveyatsu Great will work on this as well

**Comment by gradedSystem** [comment]
> @gradedSystem this PR introduces the script so it is still good IMO. Could you test if the script still works because it was created back in 2018? Here is the original issue for this #53

I have checked the scripts, it works just fine!

**Pull request merged**
